steps:
  - name: gcr.io/cloud-builders/yarn
    entrypoint: yarn
    args: ["install"]
  - name: gcr.io/cloud-builders/yarn
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/$PROJECT_ID/firebase
    args:
      - deploy
      - --project
      - "$PROJECT_ID"
      - --debug
      - --only
      - hosting
