steps:
  - name: node:16
    entrypoint: yarn
    args: ["install"]
  - name: node:16
    entrypoint: yarn
    args:
      - env
      - "${PROJECT_ID}"
      - "${_FIREBASE_WEB_API_KEY}"
      - "${_ALGOLIA_APP_ID}"
      - "${_ALGOLIA_APP_KEY}"
  - name: node:16
    entrypoint: yarn
    args: ["build"]
  - name: "gcr.io/salestube-connectors/firebase"
    args:
      - target:apply
      - hosting
      - "${_TARGET_NAME}"
      - "${_RESOURCE_IDENTIFIER}"
      - --project
      - "${PROJECT_ID}"
  - name: "gcr.io/salestube-connectors/firebase"
    args:
      - deploy
      - --project
      - "${PROJECT_ID}"
      - --debug
      - --only
      - hosting
substitutions:
  _ALGOLIA_APP_ID: ""
  _ALGOLIA_APP_KEY: ""
options:
  machineType: "N1_HIGHCPU_8"
