steps:
  - name: node:16
    entrypoint: yarn
    args: ["install"]
  - name: node:16
    entrypoint: yarn
    args:
      - env
      - "${_PROJECT_ID}"
      - "${_FIREBASE_WEB_API_KEY}"
      - "${_ALGOLIA_APP_ID}"
      - "${_ALGOLIA_APP_KEY}"
  - name: node:16
    entrypoint: yarn
    args: ["build"]
  - name: "gcr.io/${_PROJECT_ID}/firebase"
    args:
      - target:apply
      - hosting
      - "${_TARGET_NAME}"
      - "${_HOSTING_TARGET}"
      - --project
      - "${_PROJECT_ID}"
  - name: "gcr.io/${_PROJECT_ID}/firebase"
    args:
      - deploy
      - --project
      - "${_PROJECT_ID}"
      - --debug
      - --only
      - hosting
substitutions:
  _PROJECT_ID: "${PROJECT_ID}"
  _TARGET_NAME: "rowy"
  _RESOURCE_IDENTIFIER: "${_HOSTING_TARGET}"
options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
