steps:
  - name: node:16
    entrypoint: yarn
    args: ["install"]
  - name: node:16
    entrypoint: yarn
    args:
      - env
      - "${PROJECT_ID}"
      - "${_FIREBASE_WEB_API_KEY}"
      - "${_ALGOLIA_APP_ID}"
      - "${_ALGOLIA_APP_KEY}"
  - name: node:16
    entrypoint: yarn
    args: ["build"]
  - name: "gcr.io/salestube-connectors/firebase"
    args:
      - target:apply
      - hosting
      - rowy
      - project-gab.web.app
      - --project
      - "${PROJECT_ID}"
  - name: "gcr.io/salestube-connectors/firebase"
    args:
      - deploy
      - --project
      - "${PROJECT_ID}"
      - --debug
      - --only
      - hosting:project-gab.web.app
substitutions:
  _ALGOLIA_APP_ID: ""
  _ALGOLIA_APP_KEY: ""
  _SERVICE_NAME: rowy-frontend-${BRANCH_NAME}
options:
  machineType: "N1_HIGHCPU_8"
tags:
  - "$_SERVICE_NAME"
  - "$BRANCH_NAME"
