steps:
  - name: node:16
    entrypoint: yarn
    args: ["install"]
  - name: node:16
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/econometric-model-app/firebase:latest
    args:
      - deploy
      - --project
      - "$PROJECT_ID"
      - --debug
      - --only
      - hosting
